//
// Auto Generated by DLRouter on 2021-03-19 08:09:34.938834
// 

#include "trt_utils.h"
#include "bilinear_upsample.h"
#include "kernel/gpu/upsample_kernel.h"

#include <cassert>

using namespace nvinfer1;

namespace quake {
namespace framework {
namespace ops_lib {

namespace {
  static const char* BILINEAR_UPSAMPLE_PLUGIN_VERSION{"1"};
  static const char* BILINEAR_UPSAMPLE_PLUGIN_NAME{"bilinear_upsample"};
}

// Static class fields initialization
PluginFieldCollection BILINEAR_UPSAMPLE_Creator::mFC{};
std::vector<PluginField> BILINEAR_UPSAMPLE_Creator::mPluginAttributes;

REGISTER_TENSORRT_PLUGIN(BILINEAR_UPSAMPLE_Creator);

//initialize funs
BILINEAR_UPSAMPLE_Plugin::BILINEAR_UPSAMPLE_Plugin(const std::string name,int p_out_h,int p_out_w,bool p_align_corners)
  : mLayerName(name)
  , out_h(p_out_h)
  , out_w(p_out_w)
  , align_corners(p_align_corners)
{
}

BILINEAR_UPSAMPLE_Plugin::BILINEAR_UPSAMPLE_Plugin(const std::string name,const void* data, size_t length)
  : mLayerName(name)
{
  // Deserialize in the same order as serialization
  const char *d = static_cast<const char *>(data);
  const char *a = d;
  readFromBuffer(d,out_h);
  readFromBuffer(d,out_w);
  readFromBuffer(d,align_corners);
  readFromBuffer(d,channel);
  readFromBuffer(d,height);
  readFromBuffer(d,width);
  readFromBuffer(d,mDataType);

  assert(d == (a + length) && "length of data mismatch");
}

void BILINEAR_UPSAMPLE_Plugin::serialize(void* buffer) const
{
  char *d = static_cast<char *>(buffer);
  const char *a = d;
  writeToBuffer(d,out_h);
  writeToBuffer(d,out_w);
  writeToBuffer(d,align_corners);
  writeToBuffer(d,channel);
  writeToBuffer(d,height);
  writeToBuffer(d,width);
  writeToBuffer(d,mDataType);

  assert(d == a + getSerializationSize());
}

size_t BILINEAR_UPSAMPLE_Plugin::getSerializationSize() const
{
  return sizeof(mDataType)+2*sizeof(int)+1*sizeof(bool)+3*sizeof(int);
}

const char* BILINEAR_UPSAMPLE_Plugin::getPluginType() const
{
  return BILINEAR_UPSAMPLE_PLUGIN_NAME;
}

const char* BILINEAR_UPSAMPLE_Plugin::getPluginVersion() const
{
  return BILINEAR_UPSAMPLE_PLUGIN_VERSION;
}

int BILINEAR_UPSAMPLE_Plugin::initialize()
{
  return 0;
}

void BILINEAR_UPSAMPLE_Plugin::terminate() {}

void BILINEAR_UPSAMPLE_Plugin::destroy()
{
  delete this;
}

//runtime functions
int BILINEAR_UPSAMPLE_Plugin::getNbOutputs() const
{
  return 1;
}

Dims BILINEAR_UPSAMPLE_Plugin::getOutputDimensions(int index, const Dims* inputs, int nbInputDims)
{
  // Validate input arguments, Please set output shapes manually
  assert(nbInputDims == 1);
  
  channel=inputs[0].d[0];
  height=inputs[0].d[1];
  width=inputs[0].d[2];
  if(index==0){
    return DimsCHW{channel,out_h,out_w};
  }
}

size_t BILINEAR_UPSAMPLE_Plugin::getWorkspaceSize(int maxBatchSize) const
{
  return maxBatchSize*(0);
}

int BILINEAR_UPSAMPLE_Plugin::enqueue(int batchSize, const void* const* inputs, void** outputs, void* workspace, cudaStream_t stream)
{
  if (mDataType == DataType::kFLOAT){
    bilinear_upsample(stream,
      reinterpret_cast<const float*>(inputs[0]),
      reinterpret_cast<float*>(outputs[0]),
      batchSize,
      channel,
      height,
      width,
      out_h,
      out_w,
      align_corners);
  } else if (mDataType == DataType::kHALF){
    bilinear_upsample(stream,
      reinterpret_cast<const __half*>(inputs[0]),
      reinterpret_cast<__half*>(outputs[0]),
      batchSize,
      channel,
      height,
      width,
      out_h,
      out_w,
      align_corners);
  }
  return 0;
}

//config functions
void BILINEAR_UPSAMPLE_Plugin::configureWithFormat(const Dims* inputs, int nbInputs, const Dims* outputs, int nbOutputs, DataType type, PluginFormat format, int)
{
  // Validate input arguments
  assert(nbInputs == 1);
  assert(nbOutputs == 1);
  channel=inputs[0].d[0];
  height=inputs[0].d[1];
  width=inputs[0].d[2];
  mDataType = type;
}

bool BILINEAR_UPSAMPLE_Plugin::supportsFormat(DataType type, PluginFormat format) const
{
  return true;
}


//describe functions
IPluginV2* BILINEAR_UPSAMPLE_Plugin::clone() const
{
  return new BILINEAR_UPSAMPLE_Plugin(mLayerName,out_h,out_w,align_corners);
}

void BILINEAR_UPSAMPLE_Plugin::setPluginNamespace(const char* libNamespace)
{
  mNamespace = libNamespace;
}

const char* BILINEAR_UPSAMPLE_Plugin::getPluginNamespace() const
{
  return mNamespace.c_str();
}


//creator functions
BILINEAR_UPSAMPLE_Creator::BILINEAR_UPSAMPLE_Creator()
{
  mPluginAttributes.emplace_back(PluginField("out_h",nullptr,PluginFieldType::kINT32,1));
  mPluginAttributes.emplace_back(PluginField("out_w",nullptr,PluginFieldType::kINT32,1));
  mPluginAttributes.emplace_back(PluginField("align_corners",nullptr,PluginFieldType::kINT32,1));
  // Fill PluginFieldCollection with PluginField arguments metadata
  mFC.nbFields = mPluginAttributes.size();
  mFC.fields = mPluginAttributes.data();
}

const char* BILINEAR_UPSAMPLE_Creator::getPluginName() const
{
  return BILINEAR_UPSAMPLE_PLUGIN_NAME;
}

const char* BILINEAR_UPSAMPLE_Creator::getPluginVersion() const
{
  return BILINEAR_UPSAMPLE_PLUGIN_VERSION;
}

const PluginFieldCollection* BILINEAR_UPSAMPLE_Creator::getFieldNames()
{
  return &mFC;
}

IPluginV2* BILINEAR_UPSAMPLE_Creator::createPlugin(const char* name, const PluginFieldCollection* fc)
{
  int out_h=0;
  int out_w=0;
  bool align_corners=0;
  const PluginField* fields = fc->fields;

  // Parse fields from PluginFieldCollection
  assert(fc->nbFields == 3);
  for (int i = 0; i < fc->nbFields; i++){
    if (strcmp(fields[i].name, "out_h") == 0) {
      assert(fields[i].type == PluginFieldType::kINT32);
      out_h = *(static_cast<const int*>(fields[i].data));
    }else if (strcmp(fields[i].name, "out_w") == 0) {
      assert(fields[i].type == PluginFieldType::kINT32);
      out_w = *(static_cast<const int*>(fields[i].data));
    }else if (strcmp(fields[i].name, "align_corners") == 0) {
      assert(fields[i].type == PluginFieldType::kINT32);
      align_corners = *(static_cast<const bool*>(fields[i].data));
    }
  }

  BILINEAR_UPSAMPLE_Plugin* obj = new BILINEAR_UPSAMPLE_Plugin(name,out_h,out_w,align_corners);
  obj->setPluginNamespace(mNamespace.c_str());
  return obj;
}

IPluginV2* BILINEAR_UPSAMPLE_Creator::deserializePlugin(const char* name, const void* serialData, size_t serialLength)
{
  BILINEAR_UPSAMPLE_Plugin* obj = new BILINEAR_UPSAMPLE_Plugin(name, serialData, serialLength);
  obj->setPluginNamespace(mNamespace.c_str());
  return obj;
}

void BILINEAR_UPSAMPLE_Creator::setPluginNamespace(const char* libNamespace)
{
  mNamespace = libNamespace;
}

const char* BILINEAR_UPSAMPLE_Creator::getPluginNamespace() const
{
  return mNamespace.c_str();
}

} // namespace ops_lib
} // namespace framework
} // namespace quake
